import {mongo, Types} from 'mongoose';
import {Readable} from 'stream';
import {getGfs} from '../config/multer.js';
import {v4 as uuidv4} from 'uuid';

// Function to stream the file buffer into GridFS
export const uploadFileToGridFS = (fileBuffer: Buffer, repoName: string, commitMessage?: string): Promise<mongo.BSON.ObjectId> => {
    return new Promise((resolve, reject) => {
        const gfs = getGfs();
        if(!gfs) return reject(new Error("GridFS not initialized."));

        const readableStream = Readable.from(fileBuffer);

        // unique name for the file is the combination of repository name and commit hash generated by uuid 
        const fileUniqueName = `${repoName}-${uuidv4()}.zip`

        const uploadStream = gfs.openUploadStream(
            fileUniqueName, 
            {
                chunkSizeBytes: 1024*255, // 255 kB
                metadata: {
                    repoName: repoName,
                    commitMessage: commitMessage
                },
                contentType: 'application/zip' // or file.mimetype
            });

        // Start piping
        const fileId: Types.ObjectId = uploadStream.id; // capture id immediately to avoid garbage :)
        readableStream.pipe(uploadStream);

        // Handle events
        uploadStream.on('error', (error) => {
            reject(error);
        });

        uploadStream.on('finish', () => {
            resolve(fileId); // use the captured id
        });
    });
};